### ISSUE TITLE
Invalid config: Invalid module config entries in config file

### ISSUE THREAD

**Issue by ortiga88** [prometheus-pve/prometheus-pve-exporter#101]
I have the following configuration directly in proxmox:

```
default:
#    user: root@pam!root
    user: root@pam
    token_name: "...."
    token_value: "......"

scrape_configs:
  - job_name: 'pve'
    static_configs:
      - targets:
        - 10.0.0.200:9221
        - 10.0.0.240:9221
        - 10.0.0.250:9221
    metrics_path: /pve
```
But I get the following error and the yml is correctly undetermined, what can it be? :

```
usage: pve_exporter [-h] [--collector.status] [--collector.version]
                    [--collector.node] [--collector.cluster]
                    [--collector.resources] [--collector.config]
                    [config] [port] [address]
pve_exporter: error: Invalid config: Invalid module config entries in config file
  - scrape_configs: Invalid config: Not a dictionary. Check the syntax of the YAML config file.

```

**Comment by znerol** [comment]
`scrape_config` should go into the prometheus configuration file `prometheus.pyml`. The module config (`default`) belongs into the Prometheus PVE Exporter configuration file (`pve.yml`). It is not possible to put both sections into the same file.

**Comment by ortiga88** [comment]
ok I have configured it as follows:

baremetal proxmox server 1 docker:
pve.yml:

default:
     user: root
     password: ........
     verify_ssl: false


when I put this route I should see the metrics:

http: // proxmox: 9221 / pve

it gives me the following error:

```
Exception thrown while rendering view
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 169, in _new_conn
    conn = connection.create_connection(
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 96, in create_connection
    raise err
  File "/usr/lib/python3.8/site-packages/urllib3/util/connection.py", line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 699, in urlopen
    httplib_response = self._make_request(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 382, in _make_request
    self._validate_conn(conn)
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 1010, in _validate_conn
    conn.connect()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 353, in connect
    conn = self._new_conn()
  File "/usr/lib/python3.8/site-packages/urllib3/connection.py", line 181, in _new_conn
    raise NewConnectionError(
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7f63c99662e0>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/lib/python3.8/site-packages/urllib3/connectionpool.py", line 755, in urlopen
    retries = retries.increment(
  File "/usr/lib/python3.8/site-packages/urllib3/util/retry.py", line 573, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='localhost', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63c99662e0>: Failed to establish a new connection: [Errno 111] Connection refused'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/pve_exporter/http.py", line 96, in view
    return view_registry[endpoint](**params)
  File "/usr/lib/python3.8/site-packages/pve_exporter/http.py", line 38, in on_pve
    output = collect_pve(self._config[module], target, self._collectors)
  File "/usr/lib/python3.8/site-packages/pve_exporter/collector.py", line 316, in collect_pve
    pve = ProxmoxAPI(host, **config)
  File "/usr/lib/python3.8/site-packages/proxmoxer/core.py", line 127, in __init__
    self._backend = importlib.import_module('.backends.%s' % backend, 'proxmoxer').Backend(host, **kwargs)
  File "/usr/lib/python3.8/site-packages/proxmoxer/backends/https.py", line 198, in __init__
    self.auth = ProxmoxHTTPAuth(self.base_url, user, password, verify_ssl, timeout)
  File "/usr/lib/python3.8/site-packages/proxmoxer/backends/https.py", line 66, in __init__
    self._getNewTokens(password=password)
  File "/usr/lib/python3.8/site-packages/proxmoxer/backends/https.py", line 74, in _getNewTokens
    response_data = requests.post(self.base_url + "/access/ticket",
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 119, in post
    return request('post', url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.8/site-packages/requests/sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.8/site-packages/requests/adapters.py", line 516, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='localhost', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7f63c99662e0>: Failed to establish a new connection: [Errno 111] Connection refused'))
192.168.10.11 - - [06/Dec/2021 10:44:24] "GET /pve HTTP/1.1" 500 -
```

what happen ??

**Comment by znerol** [comment]
Please use the following schema to construct the URL (mentioned in the README): `http://<prometheus-pve-host>:9221/pve?target=<proxmox-host>`.

Assuming you have the following IPs
* IP of proxmox host: 192.168.22.33
* IP of prometheus pve (in docker container): 10.20.30.40

Then that would result in the following URL: `http://10.20.30.40/pve?target=192.168.22.33`

Also please note that the issue tracker is not a support forum. Post further questions on stackoverflow and label them with `prometheus`. Closing this issue.

**Comment by ortiga88** [comment]
proxmox :10.0.0.2
exporter: 10.0.0.240

prometheus.yml:

```
global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
#  - job_name: "prometheus"
#    static_configs:
#      - targets: ["localhost:9090"]

  - job_name: "pve"
    static_configs:
      - targets:
        - 10.0.0.240
    metrics_path: /pve
    params:
      module: [default]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 10.0.0.240:9221
```


curl http://10.0.0.240:9221/pve?target=10.0.0.2

show metric correct

in grafsna I don't see anything please help me

![image](https://user-images.githubusercontent.com/26000087/144843597-19fba67a-d981-40b1-afc1-a9bf9ad2dbb9.png)
