### ISSUE TITLE
Node exporter not exporting any data

### ISSUE THREAD

**Issue by joennespreuwers** [prometheus-pve/prometheus-pve-exporter#104]
I have a proxmox running with a portainer vm with Grafana and Prometheus. I was trying to export proxmox data to my Grafana but the exposed endpoint on proxmox is not providing any info at all about my vm.

Here's a copypaste of the end of my exposed endpoint, It seems that it not possible to get the info but I dont know what is causing the issue.

```
pve_collection_duration_seconds_created{module="default"} 1.6397829755308063e+09
# HELP pve_request_errors_total Errors in requests to PVE exporter
# TYPE pve_request_errors_total counter
pve_request_errors_total{module="default"} 0.0
# HELP pve_request_errors_created Errors in requests to PVE exporter
# TYPE pve_request_errors_created gauge
pve_request_errors_created{module="default"} 1.6397829755307894e+09
```

**Comment by znerol** [comment]
Please take a look at `stderr` (i.e., logs) generated by pve exporter.

**Comment by joennespreuwers** [comment]
This is `journalctl -u prometheus-pve-exporter.service`:

```
-- Journal begins at Mon 2021-08-23 12:34:46 CEST, ends at Sat 2021-12-18 23:33:52 CET. --
Dec 13 18:40:47 jrtms-galaxy systemd[1]: Started Prometheus exporter for Proxmox VE.
Dec 13 18:40:48 jrtms-galaxy pve_exporter[679449]:  * Running on http://:9221/ (Press CTRL+C to quit)
Dec 13 18:41:21 jrtms-galaxy pve_exporter[679449]: 192.168.0.153 - - [13/Dec/2021 18:41:21] "GET / HTTP/1.1" 200 -
Dec 13 18:41:21 jrtms-galaxy pve_exporter[679449]: 192.168.0.153 - - [13/Dec/2021 18:41:21] "GET /favicon.ico HTTP/1.1" 404 -
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]: Exception thrown while rendering view
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]: Traceback (most recent call last):
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 169, in _new_conn
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     conn = connection.create_connection(
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 96, in create_connection
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     raise err
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/util/connection.py", line 86, in create_connection
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     sock.connect(sa)
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]: socket.timeout: timed out
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]: During handling of the above exception, another exception occurred:
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]: Traceback (most recent call last):
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 699, in urlopen
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     httplib_response = self._make_request(
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 382, in _make_request
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     self._validate_conn(conn)
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/connectionpool.py", line 1012, in _validate_conn
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     conn.connect()
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:   File "/usr/lib/python3/dist-packages/urllib3/connection.py", line 353, in connect
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]:     conn = self._new_conn()
```

**Comment by znerol** [comment]
```
Dec 13 18:41:39 jrtms-galaxy pve_exporter[679449]: socket.timeout: timed out
```

This indicates that pve exporter cannot reach proxmox. If there is traffic filtering (firewall) on the way between pve exporter and proxmox, please try to enable logging in order to see where connections are dropped. Also check input rules on the proxmox firewall.

**Comment by joennespreuwers** [comment]
Could you maybe guide me into logging this, because the node_exporter is running on the same machine as proxmox, so that shouldn't form an issue right?

**Comment by znerol** [comment]
Lately, I've been trying to keep volume on support requests down in the issue tracker. Github issues are really great for triaging software defects and get them fixed. They are not so great for giving support. This is mainly because people will not find existing answers to their questions because nobody will search through closed issues.

Thus I ask you kindly to go through the readme a second time and maybe through some blog posts other people have written about pve exporter. If you cannot find a working config, then I recommend you to post a question on stackoverflow. Describe your setup (redact personal data), describe what you tried, describe what you expect, describe what you got instead. Tag the question with the `prometheus` and `proxmox` labels.

You may post a link to your question here. I'll gonna take a look if time permits.
