### ISSUE TITLE
OSError: Could not find a suitable TLS CA certificate bundle

### ISSUE THREAD

**Issue by SeanOMik** [prometheus-pve/prometheus-pve-exporter#147]
I have pve-exporter deployed in a k3s cluster, but it can't scrape from proxmox. I'm using the docker image that shown on the readme (`prompve/prometheus-pve-exporter:latest`). It appears to be something to do with verifying https certs, but I have disabled ssl verification so I'm confused about why it would even be getting to a step of checking certificates. This is a complete log:
```
[2023-05-11 04:48:35 +0000] [7] [INFO] Starting gunicorn 20.1.0
[2023-05-11 04:48:35 +0000] [7] [INFO] Listening at: http://0.0.0.0:9221 (7)
[2023-05-11 04:48:35 +0000] [7] [INFO] Using worker: threads
[2023-05-11 04:48:35 +0000] [8] [INFO] Booting worker with pid: 8
Exception thrown while rendering view
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pve_exporter/http.py", line 96, in view
    return view_registry[endpoint](**params)
  File "/usr/lib/python3.10/site-packages/pve_exporter/http.py", line 38, in on_pve
    output = collect_pve(self._config[module], target, self._collectors)
  File "/usr/lib/python3.10/site-packages/pve_exporter/collector.py", line 332, in collect_pve
    return generate_latest(registry)
  File "/usr/lib/python3.10/site-packages/prometheus_client/exposition.py", line 198, in generate_latest
    for metric in registry.collect():
  File "/usr/lib/python3.10/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/usr/lib/python3.10/site-packages/pve_exporter/collector.py", line 45, in collect
    for entry in self._pve.cluster.status.get():
  File "/usr/lib/python3.10/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
  File "/usr/lib/python3.10/site-packages/proxmoxer/core.py", line 144, in _request
    resp = self._store["session"].request(method, url, data=data, params=params)
  File "/usr/lib/python3.10/site-packages/proxmoxer/backends/https.py", line 229, in request
    return super().request(
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 460, in send
    self.cert_verify(conn, request.url, verify, cert)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 263, in cert_verify
    raise OSError(
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: false
```
I've tried to disable ssl verification with the config variable `verify_ssl` and also the environmental variable `PVE_VERIFY_SSL`, both with the same result.

I really appreciate any help you can provide.

**Comment by znerol** [comment]
Thanks for taking the time to report this issue.

This looks like it is coming from the python [requests](https://pypi.org/project/requests) package. Regrettably I cannot reproduce this problem. What happens when you run the image in `docker` or `podman`?

Also what happens when you run this python oneliner inside the image:

```
podman run -it --rm --entrypoint python prompve/prometheus-pve-exporter:latest -c 'import requests; print(requests.get("https://github.com").status_code)'
```

(Replace `podman` by `docker` if appropriate).

**Comment by znerol** [comment]
Could you try setting `PVE_VERIFY_SSL` to `0` (instead of `false`)? It looks like the `requests` module does something funny when it thinks that the `verify` param is a string (not a boolean):

https://github.com/psf/requests/blob/d3d504436ef0c2ac7ec8af13738b04dcc8c694be/requests/adapters.py#L253-L258

**Comment by SeanOMik** [comment]
> Could you try setting PVE_VERIFY_SSL to 0 (instead of false)? It looks like the requests module does something funny when it thinks that the verify param is a string (not a boolean):

afaik, environment variables are always strings. I tried to set it to `0` instead of `false` and I got a different error. This looks like its attempting to verify the certs:
```
Traceback (most recent call last):
  File "/usr/lib/python3.10/site-packages/pve_exporter/http.py", line 96, in view
    return view_registry[endpoint](**params)
  File "/usr/lib/python3.10/site-packages/pve_exporter/http.py", line 38, in on_pve
    output = collect_pve(self._config[module], target, self._collectors)
  File "/usr/lib/python3.10/site-packages/pve_exporter/collector.py", line 316, in collect_pve
    pve = ProxmoxAPI(host, **config)
  File "/usr/lib/python3.10/site-packages/proxmoxer/core.py", line 210, in __init__
    self._backend = importlib.import_module(f".backends.{backend}", "proxmoxer").Backend(
  File "/usr/lib/python3.10/site-packages/proxmoxer/backends/https.py", line 302, in __init__
    self.auth = ProxmoxHTTPAuth(
  File "/usr/lib/python3.10/site-packages/proxmoxer/backends/https.py", line 59, in __init__
    self._get_new_tokens(password=password, otp=otp)
  File "/usr/lib/python3.10/site-packages/proxmoxer/backends/https.py", line 70, in _get_new_tokens
    response_data = requests.post(
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 115, in post
    return request("post", url, data=data, json=json, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/api.py", line 59, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 587, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/lib/python3.10/site-packages/requests/sessions.py", line 701, in send
    r = adapter.send(request, **kwargs)
  File "/usr/lib/python3.10/site-packages/requests/adapters.py", line 563, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='192.168.87.28', port=8006): Max retries exceeded with url: /api2/json/access/ticket (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY
_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1007)')))
```

> This looks like it is coming from the python [requests](https://pypi.org/project/requests) package. Regrettably I cannot reproduce this problem. What happens when you run the image in docker or podman?

It worked in docker. I did run into an authorization error which I fixed in the configuration. I tried to use that configuration with the one in kubernetes, and only specified that it shouldn't verify ssl in the config file, and it worked! I think since I had it as an environmental variable AND a config value and something was not happy. 

Thanks for the help!

**Comment by znerol** [comment]
:+1:

**Comment by luthes** [comment]
Happened to come to this issue from Google while facing a similar issue. I'm running in Kubernetes and using env vars to configure the connector. It does seem like there is some an issue with env vars configuring `PVE_VERIFY_SSL`, same as above basically, it's (probably) a string, and needs to be converted to a bool for the env vars to work.
