### ISSUE TITLE
requests.exceptions.ReadTimeout

### ISSUE THREAD

**Issue by Borillion** [prometheus-pve/prometheus-pve-exporter#153]
Having issues with this working, running into a timeout. Any ideas as to what may be causing this?

```
Exception thrown while rendering view
Traceback (most recent call last):
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/connection.py", line 454, in getresponse
    httplib_response = super().getresponse()
  File "/usr/lib/python3.9/http/client.py", line 1347, in getresponse
    response.begin()
  File "/usr/lib/python3.9/http/client.py", line 307, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.9/http/client.py", line 268, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
  File "/usr/lib/python3.9/ssl.py", line 1241, in recv_into
    return self.read(nbytes, buffer)
  File "/usr/lib/python3.9/ssl.py", line 1099, in read
    return self._sslobj.read(len, buffer)
socket.timeout: The read operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/requests/adapters.py", line 486, in send
    resp = conn.urlopen(
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/connectionpool.py", line 844, in urlopen
    retries = retries.increment(
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/util/retry.py", line 470, in increment
    raise reraise(type(error), error, _stacktrace)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/connectionpool.py", line 790, in urlopen
    response = self._make_request(
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/urllib3/connectionpool.py", line 370, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPSConnectionPool(host='localhost', port=8006): Read timed out. (read timeout=5)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/pve_exporter/http.py", line 96, in view
    return view_registry[endpoint](**params)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/pve_exporter/http.py", line 38, in on_pve
    output = collect_pve(self._config[module], target, self._collectors)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/pve_exporter/collector.py", line 332, in collect_pve
    return generate_latest(registry)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/prometheus_client/exposition.py", line 198, in generate_latest
    for metric in registry.collect():
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/prometheus_client/registry.py", line 97, in collect
    yield from collector.collect()
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/pve_exporter/collector.py", line 289, in collect
    for vmdata in self._pve.nodes(node['node']).qemu.get():
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/core.py", line 169, in get
    return self(args)._request("GET", params=params)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/core.py", line 144, in _request
    resp = self._store["session"].request(method, url, data=data, params=params)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/proxmoxer/backends/https.py", line 229, in request
    return super().request(
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/requests/sessions.py", line 589, in request
    resp = self.send(prep, **send_kwargs)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/requests/sessions.py", line 703, in send
    r = adapter.send(request, **kwargs)
  File "/opt/prometheus-pve-exporter/lib/python3.9/site-packages/requests/adapters.py", line 532, in send
    raise ReadTimeout(e, request=request)
requests.exceptions.ReadTimeout: HTTPSConnectionPool(host='localhost', port=8006): Read timed out. (read timeout=5)
```

**Comment by Borillion** [comment]
One of the nodes was missing an SSL node somehow, and that was causing the exporter to break.
