### ISSUE TITLE
permissions issue

### ISSUE THREAD

**Issue by lgwapnitsky** [prometheus-pve/prometheus-pve-exporter#69]
Receiving the following when trying to access my metrics

```
proxmoxer.core.ResourceException: 403 Forbidden: Permission check failed (/, Sys.Audit) - b'{"data":null}'                                                                                                  
10.150.33.152 - - [14/Apr/2021 07:41:23] "GET /pve?module=default HTTP/1.1" 500 -
Exception thrown while rendering view
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/pve_exporter/http.py", line 96, in view
    return view_registry[endpoint](**params)
  File "/usr/local/lib/python3.7/dist-packages/pve_exporter/http.py", line 38, in on_pve
    output = collect_pve(self._config[module], target, self._collectors)
  File "/usr/local/lib/python3.7/dist-packages/pve_exporter/collector.py", line 332, in collect_pve
    return generate_latest(registry)
  File "/usr/local/lib/python3.7/dist-packages/prometheus_client/exposition.py", line 177, in generate_latest
    for metric in registry.collect():
  File "/usr/local/lib/python3.7/dist-packages/prometheus_client/registry.py", line 83, in collect
    for metric in collector.collect():
  File "/usr/local/lib/python3.7/dist-packages/pve_exporter/collector.py", line 45, in collect
    for entry in self._pve.cluster.status.get():
  File "/usr/local/lib/python3.7/dist-packages/proxmoxer/core.py", line 105, in get
    return self(args)._request("GET", params=params)
  File "/usr/local/lib/python3.7/dist-packages/proxmoxer/core.py", line 94, in _request
    resp.reason, resp.content))
```

my config file is as such:

```
user: "prometheus@pve"
   token_name: prometheus
   token_value: "token_value"
   verify_ssl: false
```

The user has PVEAuditor permissions, and the group of which it is a member has access to the whole tree.

**Comment by lgwapnitsky** [comment]
nevermind...was a token issue.  my bad
